### ISSUE TITLE
Header image does not scale in mobile view

### ISSUE THREAD

**Issue by ginsterbusch** [Themekraft/Custom-Community#282]
The header image does not scale down in mobile and tablet view, as it's supposed to be.

Bug is caused by the CSS code for .site-inner-header. Setting display to block instead of the default table value fixes it.

**Comment by ginsterbusch** [comment]
Hotfix for all versions < 2.0.27:

```css
.site-header-inner {
  display: block;
}
```
